import {
  Container,
  Button,
  Text,
  Card,
  Divider,
  Group,
  Title,
  Blockquote,
  Badge,
  Space,
  Flex,
} from "@mantine/core";

interface QuestionCardProps {
  questionNum: number;
  totalQuestionNum: number;
  prompt: string[];
  promptReadIndex: number;
  tags: string[];
}

export default function QuestionCard({
  questionNum,
  totalQuestionNum,
  prompt,
  promptReadIndex,
  tags,
}: QuestionCardProps) {
  return (
    <Container size="xs" style={{ width: "100%" }}>
      <Card withBorder radius="md" shadow="md">
        <Group position="apart">
          <Group spacing={9}>
            <Title order={1} pb={8}>
              Q{questionNum}
            </Title>
            <Title order={3} color="dimmed">
              of {totalQuestionNum}
            </Title>
          </Group>
          <Text color="dimmed" italic fz="sm">
            generated by AI
          </Text>
        </Group>
        <Card.Section pb="xs">
          <Divider color="blue" size="lg" />
        </Card.Section>
        <Space h="sm" />
        <Group>
          {tags.map((tag) => (
            <Badge key={tag}>{tag}</Badge>
          ))}
        </Group>
        <Blockquote>
          <Prompt promptReadIndex={promptReadIndex} prompt={prompt} />
        </Blockquote>
        <Group position="right">
          <Button variant="subtle" radius="md">
            Skip question
          </Button>
        </Group>
      </Card>
    </Container>
  );
}

interface PromptProps {
  prompt: string[];
  promptReadIndex: number;
}
function Prompt({ prompt, promptReadIndex }: PromptProps) {
  const words = prompt.map((word, index) => {
    let color = "dimmed";
    if (promptReadIndex == index) {
      color = "violet";
    } else if (promptReadIndex > index) {
      color = "dark";
    }
    return (
      <Text weight={600} fz="xl" component="span" color={color} key={index}>
        {word}&nbsp;
      </Text>
    );
  });

  return <Flex wrap={"wrap"}>{words}</Flex>;
}
