// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai/analyse": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai"
                ],
                "summary": "analyse an answer to a question",
                "parameters": [
                    {
                        "description": "Question and Answer to be analysed by AI",
                        "name": "QAPair",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AnalysisRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.Analysis"
                        }
                    }
                }
            }
        },
        "/application/create": {
            "post": {
                "description": "an application has some properties",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Create an application for the user",
                "parameters": [
                    {
                        "description": "Application",
                        "name": "ApplicationCreateBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ApplicationCreateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ApplicationCreateResponse"
                        }
                    }
                }
            }
        },
        "/application/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Get user's applications",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "Ping the server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/healthcheck": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Check if a user is signed in",
                "responses": {
                    "200": {
                        "description": "if signed in ` + "`" + `{\"success\": true}` + "`" + `"
                    },
                    "401": {
                        "description": "if not signed in"
                    }
                }
            }
        },
        "/user/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Sign a user",
                "parameters": [
                    {
                        "description": "Password must be atleast 6 characters.",
                        "name": "SignInBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserCredentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserSigninResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid Credentials"
                    }
                }
            }
        },
        "/user/signout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Sign a user out of dancord",
                "responses": {
                    "200": {
                        "description": "on successful signout"
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "description": "Insert description here",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Sign a user up to dancord",
                "parameters": [
                    {
                        "description": "Password must be atleast 6 characters.",
                        "name": "SignUpBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserCredentials"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserSigninResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ApplicationCreateBody": {
            "type": "object",
            "required": [
                "jobDescription",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "SafetyCulture is an Australian-based global technology company that specialises in building inspection apps for the web and mobile devices."
                },
                "icon": {
                    "description": "icon link?",
                    "type": "string",
                    "example": "https://www.safetyculture.com/wp-content/uploads/2020/10/safetyculture-logo.svg"
                },
                "jobDescription": {
                    "type": "string",
                    "example": "Looking for an engineer to join our team."
                },
                "name": {
                    "type": "string",
                    "example": "SafetyCulture"
                }
            }
        },
        "ApplicationCreateResponse": {
            "type": "object",
            "required": [
                "jobDescription",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "SafetyCulture is an Australian-based global technology company that specialises in building inspection apps for the web and mobile devices."
                },
                "icon": {
                    "type": "string",
                    "example": "https://www.safetyculture.com/wp-content/uploads/2020/10/safetyculture-logo.svg"
                },
                "id": {
                    "type": "string",
                    "example": "1337"
                },
                "jobDescription": {
                    "type": "string",
                    "example": "Looking for an engineer to join our team."
                },
                "name": {
                    "type": "string",
                    "example": "SafetyCulture"
                }
            }
        },
        "UserCredentials": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "daniel321"
                },
                "username": {
                    "type": "string",
                    "example": "daniel"
                }
            }
        },
        "UserSigninResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1337"
                }
            }
        },
        "handlers.AnalysisRequest": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                }
            }
        },
        "service.Analysis": {
            "type": "object",
            "properties": {
                "bad": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "good": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "prepper API",
	Description:      "Backend API sepcifications for prepper",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
